selectorMode: fzf
repos:
  ofw-calendar-service:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: ~/code/cal_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-core-api:
    defaultBranch: master
    zoxideFolders:
      - src/main/resources/db/changelog/changes
    worktreeTargetDir: /code/core_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-public-api:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/pub_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-web-appv2:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/front_end_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-event-service:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/event_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-notification-api:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/notification_api_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-notification-processor:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/notification_processor_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-segment:
    defaultBranch: master
    zoxideFolders:
    worktreeTargetDir: /code/segment_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-shared-tools:
    defaultBranch: main
    zoxideFolders:
    worktreeTargetDir: /code/ofw-shared-tools-work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-api-common:
    defaultBranch: main
    zoxideFolders:
    worktreeTargetDir: /code/common_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  ofw-eng-api-tests:
    defaultBranch: main
    zoxideFolders:
    worktreeTargetDir: /code/api-tests
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  treekanga:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/treekanga_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    bareRepoName: .bare
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  sesh:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/sesh_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    bareRepoName: .bare
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  snap:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/snap_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  rolo:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/rolo_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  dgsimgo:
    defaultBranch: main 
