#undef TAPPING_TERM
#define TAPPING_TERM 140

#define COMBO_TERM 20

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "wavoD/B4Ewnv"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 7

#define RGB_MATRIX_STARTUP_SPD 60

